import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
import Link from "next/link";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body >
        <nav>
          <Link className="nav-link" href="/">홈 |</Link>
          <Link className="nav-link" href="/article"> 게시글 |</Link>
          <Link className="nav-link" href="/about"> 소개 |</Link>
          <Link href={"/user/login"}> 로그인 |</Link>
          <Link href={"/user/logout"}> 로그아웃</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
