spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: CLIENT_ID
  mail:
    host: smtp.gmail.com
    port: 587
    username: dhxnejqls13
    password: nkzwggyavgdirplb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
custom:
  randomPW: ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789
  security:
    oauth2:
      client:
        registration:
          kakao:
            devUser:
              oauthId: oauthId
              nickname: nickname
  jwt:
    secretKey: aebjhfwajehvjasbdluwevdasvdfjlegavksdjgvalkejgsf